# ベースイメージの選択
FROM pytorch/pytorch:latest

# コンテナ内のワークディレクトリの宣言
WORKDIR /app
# ホストのファイルをコンテナ内にコピー
COPY ./requirements.txt /app

# コマンドの実行 (pip)
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt 

# ホスト側のディレクトリをマウントする代わりに、approotの中身を /app/にコピー
COPY ./approot/. /app/.
